logging:
  level:
    org:
      jooq: info
      springframework:
        web: info

---
spring:
  flyway:
    create-schemas: true
    schemas:
      - cinema
  jooq:
    sql-dialect: h2

---
graphql:
  tools:
    schema-location-pattern: io/github/ermadmi78/kobby/cinema/api/cinema.graphqls

---
graphiql:
  enabled: true
  cdn:
    enabled: false
  headers:
    Authorization: Basic YWRtaW46YWRtaW4=

---
graphql.playground:
  enabled: true
  cdn:
    enabled: false
  settings:
    request.credentials: include
  headers:
    Authorization: Basic YWRtaW46YWRtaW4=

---
voyager:
  enabled: true
  cdn:
    enabled: false